version: '3'

services:
  postgres:
    env_file:
      - .env
    hostname: had_postgres
    container_name: had_postgres
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: had_postgres
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
      - ${POSTGRES_BACKUPS}:/backups
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"

  redis:
    env_file: .env
    hostname: ${REDIS_HOST}
    container_name: ${REDIS_HOST}
    image: library/redis:6.0
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --appendonly yes
    volumes:
      - ${REDIS_DATA}:/data

  rabbitmq:
    env_file: .env
    hostname: ${RABBITMQ_HOST}
    container_name: ${RABBITMQ_HOST}
    image: library/rabbitmq:3.8.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
    ports:
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
      - "${RABBITMQ_PORT}:5672"
    volumes:
      - "${RABBITMQ_DIR}:/var/lib/rabbitmq"


