version: '3'

services:

  had_app: &had_app
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    hostname: had_app
    container_name: had_app
    depends_on:
      - had_postgres
      - had_redis
      - had_rabbitmq
    volumes:
      - .:/app:z
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /start

  had_celeryworker:
    <<: *had_app
    hostname: had_celeryworker
    container_name: had_celeryworker
    depends_on:
      - had_app
    env_file:
      - .env
    ports: [ ]
    command: /start-celeryworker

  had_celerybeat:
    <<: *had_app
    hostname: had_celerybeat
    container_name: had_celerybeat
    depends_on:
      - had_app
    env_file:
      - .env
    ports: [ ]
    command: /start-celerybeat

  had_flower:
    <<: *had_app
    hostname: had_flower
    container_name: had_flower
    depends_on:
      - had_app
    env_file:
      - .env
    ports:
      - "5555:5555"
    command: /start-flower


  had_postgres:
    hostname: had_postgres
    container_name: had_postgres
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: had_postgres
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
      - ${POSTGRES_BACKUPS}:/backups
    env_file:
      - .env
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"

  had_redis:
    env_file: .env
    hostname: ${REDIS_HOST}
    container_name: ${REDIS_HOST}
    image: library/redis:6.0
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --appendonly yes
    volumes:
      - ${REDIS_DATA}:/data

  had_rabbitmq:
    env_file: .env
    hostname: ${RABBITMQ_HOST}
    container_name: ${RABBITMQ_HOST}
    image: library/rabbitmq:3.8.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
    ports:
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
      - "${RABBITMQ_PORT}:5672"
    volumes:
      - "${RABBITMQ_DIR}:/var/lib/rabbitmq"

