from src.shared.domain.repository import AbstractRepository
from src.shared.domain.entities import Entity


class DjangoRepository(AbstractRepository):
    def get(self, entity: Entity): ...

    def create(self, entity: Entity): ...

    def update(self, entity: Entity): ...

    def delete(self, entity: Entity): ...

    def search(self, entity: Entity): ...
